apiVersion: rcs.dana.io/v1alpha1
kind: Capp
metadata:
  name: {{ include "platform-backend.fullname" . }}
  labels:
    {{- include "platform-backend.labels" . | nindent 4 }}
spec:
  configurationSpec:
    template:
      spec:
        containers:
          - envFrom:
              - configMapRef:
                  name: {{ include "platform-backend.fullname" . }}-{{ .Values.config.name }}
            image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            name: {{ include "platform-backend.fullname" . }}
            readinessProbe:
              tcpSocket:
                port: {{ .Values.readinessProbe.port }}
              initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
              periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            livenessProbe:
              httpGet:
                path: {{ .Values.livenessProbe.path }}
                port: {{ .Values.livenessProbe.port }}
              initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
              periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
  scaleMetric: {{ .Values.scaleMetric }}
