apiVersion: rcs.dana.io/v1alpha1
kind: Capp
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  configurationSpec:
    template:
      spec:
        containers:
          - envFrom:
              - configMapRef:
                  name: {{ .Release.Name }}-{{ .Values.authConfig.name }}
            image: {{ .Values.image }}
            imagePullPolicy: {{ .Values.imagePullPolicy }}
            name: {{ .Release.Name }}
            readinessProbe:
              tcpSocket:
                port: {{ .Values.readinessProbe.port }}
              initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
              periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            livenessProbe:
              httpGet:
                path: {{ .Values.livenessProbe.path }}
                port: {{ .Values.livenessProbe.port }}
              initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
              periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
  scaleMetric: {{ .Values.scaleMetric }}
